version: '3.2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    env_file:
      - ./.env
    networks:
      - attendizenet
      - jupyterhub-production
    volumes:
      - .:/usr/share/nginx/html/attendize
    depends_on:
      - php
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:100jahre.akaflieg.tu-darmstadt.de"
      - "traefik.docker.network=jupyterhub-production"
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/share/nginx/html/attendize
    networks: 
      - attendizenet
  composer:
    build:
      context: .
      dockerfile: Dockerfile-composer
    depends_on:
      - php
    volumes:
      - .:/usr/share/nginx/html/attendize
    networks:
      - attendizenet
  php-worker:
    build:
      context: .
      dockerfile: Dockerfile-php
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/share/nginx/html/attendize
    command: php artisan queue:work --daemon
    networks:
      - attendizenet
  db:
    image: mysql:5.7.23
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: "yes"
      MYSQL_HOST: ${DB_HOST}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "mysql-data:/var/lib/mysql"
    networks:
    - attendizenet
  redis:
    image: redis
    networks:
      - attendizenet


networks:
  attendizenet:
  jupyterhub-production:
    external: true

volumes:
    mysql-data:
